### ISSUE TITLE
select2tokenizer searches cutom valuelists differently than database valuelists

### ISSUE THREAD

**Issue by iangus** [Servoy/servoy-extra-components#9]
When backspacing a search in the tokenizer it will only search string start on a valuelist with custom values whereas it will search the entire string on a database generated valuelist. [Here](http://screencast.com/t/Bt4TrKt7l) is a video example with a custom valuelist on the left and a database valuelist on the right.

**Comment by paronne** [comment]
Are you running from develop branch or from latest release ? This issue has been already fixed in develop branch.

**Comment by iangus** [comment]
I was running from the develop branch from a week ago and now after updating to the latest develop version I am still seeing the same issue.

**Comment by iangus** [comment]
Looking into it, the problem seems to be with the method filterList in valuelist.js and not in any of the component logic. Is this fix in a newer version of Servoy that hasn't been released?

**Comment by paronne** [comment]
My bad, i fixed this directly in the master branch. See commit: https://github.com/Servoy/servoy-extra-components/commit/3229e78556681996c558a9a81333f9a02a97c70a

**Comment by iangus** [comment]
After switching to the master branch package the issue is still there, but after further testing it doesn't seem to be a difference between Custom and Database valuelist. I'm not sure what the cause is but it is very sporadic. [This video](http://www.screencast.com/t/ab0cF5uUDd) shows what I'm seeing. Valuelists with <100 values search the entire string initially but then backspacing it will only search the start. Valuelists with >100 values search more than just the start but not the entire string when searching initially and when backspacing.
